modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "extrahitboxes"
version = "${version}"
displayName = "ExtraHitboxes"
authors = "DarkPred (inspired), Pol"
description = '''
Adds the ability to have custom hitboxes with geckolib and blockbench
'''
#logoFile = ""

[[dependencies.extrahitboxes]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrahitboxes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrahitboxes]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "extrahitboxes-neoforge.mixins.json"
